# Configuration for Go Bookstore

#allowed values: development test production
env: test
bind: 0.0.0.0
port: 8081
gin_mode: test

gobookstore:
  db: book_store_test
  dsn: mongodb+srv://LordLava:LordLava2000%40@cluster0.zhq09oo.mongodb.net/?retryWrites=true&w=majority
  logpath: /Users/snehil.sinha/Documents/bookstore/log/logs_test.log

cors:
  allowed_origins: ^(localhost)(:\d{1,4}|)$